language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda_deps='pip numpy scipy networkx matplotlib nose sympy h5py'
  - conda create -q -n test-environment "python=$TRAVIS_PYTHON_VERSION" $conda_deps
  - source activate test-environment
  - pip_deps='progressbar2 nose nose-exclude codecov'
  - pip install $pip_deps
  - pip install .
before_script: # configure a headless display to test plot generation
  - "export DISPLAY=:99.0"
services:
  - xvfb
# command to run tests
script:
  - nosetests --with-coverage --cover-erase
after_success:
  - codecov
  - coveralls
