build: false

environment:
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda
    - PYTHON_VERSION: 3.5
      MINICONDA: C:\Miniconda3
    - PYTHON_VERSION: 3.6
      MINICONDA: C:\Miniconda3
    - PYTHON_VERSION: 3.7
      MINICONDA: C:\Miniconda3

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - activate
  - conda update -q conda
  - "conda create -q -n test-environment python=%PYTHON_VERSION% numpy scipy nose"
  - activate test-environment
  - pip install coverage
  - pip install -r requirements.txt

test_script:
  - nosetests
